//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator_2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CalculatorWebServicesSoap")]
    public interface CalculatorWebServicesSoap {
        
        // CODEGEN: Generating message contract since element name AddNumResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNum", ReplyAction="*")]
        Calculator_2.ServiceReference1.AddNumResponse AddNum(Calculator_2.ServiceReference1.AddNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.AddNumResponse> AddNumAsync(Calculator_2.ServiceReference1.AddNumRequest request);
        
        // CODEGEN: Generating message contract since element name SubNumResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubNum", ReplyAction="*")]
        Calculator_2.ServiceReference1.SubNumResponse SubNum(Calculator_2.ServiceReference1.SubNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.SubNumResponse> SubNumAsync(Calculator_2.ServiceReference1.SubNumRequest request);
        
        // CODEGEN: Generating message contract since element name MulNumResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MulNum", ReplyAction="*")]
        Calculator_2.ServiceReference1.MulNumResponse MulNum(Calculator_2.ServiceReference1.MulNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MulNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.MulNumResponse> MulNumAsync(Calculator_2.ServiceReference1.MulNumRequest request);
        
        // CODEGEN: Generating message contract since element name DivNumResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivNum", ReplyAction="*")]
        Calculator_2.ServiceReference1.DivNumResponse DivNum(Calculator_2.ServiceReference1.DivNumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivNum", ReplyAction="*")]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.DivNumResponse> DivNumAsync(Calculator_2.ServiceReference1.DivNumRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNum", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.AddNumRequestBody Body;
        
        public AddNumRequest() {
        }
        
        public AddNumRequest(Calculator_2.ServiceReference1.AddNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public AddNumRequestBody() {
        }
        
        public AddNumRequestBody(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.AddNumResponseBody Body;
        
        public AddNumResponse() {
        }
        
        public AddNumResponse(Calculator_2.ServiceReference1.AddNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNumResult;
        
        public AddNumResponseBody() {
        }
        
        public AddNumResponseBody(string AddNumResult) {
            this.AddNumResult = AddNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubNum", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.SubNumRequestBody Body;
        
        public SubNumRequest() {
        }
        
        public SubNumRequest(Calculator_2.ServiceReference1.SubNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public SubNumRequestBody() {
        }
        
        public SubNumRequestBody(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.SubNumResponseBody Body;
        
        public SubNumResponse() {
        }
        
        public SubNumResponse(Calculator_2.ServiceReference1.SubNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubNumResult;
        
        public SubNumResponseBody() {
        }
        
        public SubNumResponseBody(string SubNumResult) {
            this.SubNumResult = SubNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MulNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MulNum", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.MulNumRequestBody Body;
        
        public MulNumRequest() {
        }
        
        public MulNumRequest(Calculator_2.ServiceReference1.MulNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MulNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public MulNumRequestBody() {
        }
        
        public MulNumRequestBody(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MulNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MulNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.MulNumResponseBody Body;
        
        public MulNumResponse() {
        }
        
        public MulNumResponse(Calculator_2.ServiceReference1.MulNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MulNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MulNumResult;
        
        public MulNumResponseBody() {
        }
        
        public MulNumResponseBody(string MulNumResult) {
            this.MulNumResult = MulNumResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivNum", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.DivNumRequestBody Body;
        
        public DivNumRequest() {
        }
        
        public DivNumRequest(Calculator_2.ServiceReference1.DivNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivNumRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int num1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int num2;
        
        public DivNumRequestBody() {
        }
        
        public DivNumRequestBody(int num1, int num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DivNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DivNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public Calculator_2.ServiceReference1.DivNumResponseBody Body;
        
        public DivNumResponse() {
        }
        
        public DivNumResponse(Calculator_2.ServiceReference1.DivNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DivNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DivNumResult;
        
        public DivNumResponseBody() {
        }
        
        public DivNumResponseBody(string DivNumResult) {
            this.DivNumResult = DivNumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServicesSoapChannel : Calculator_2.ServiceReference1.CalculatorWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServicesSoapClient : System.ServiceModel.ClientBase<Calculator_2.ServiceReference1.CalculatorWebServicesSoap>, Calculator_2.ServiceReference1.CalculatorWebServicesSoap {
        
        public CalculatorWebServicesSoapClient() {
        }
        
        public CalculatorWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator_2.ServiceReference1.AddNumResponse Calculator_2.ServiceReference1.CalculatorWebServicesSoap.AddNum(Calculator_2.ServiceReference1.AddNumRequest request) {
            return base.Channel.AddNum(request);
        }
        
        public string AddNum(int num1, int num2) {
            Calculator_2.ServiceReference1.AddNumRequest inValue = new Calculator_2.ServiceReference1.AddNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.AddNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Calculator_2.ServiceReference1.AddNumResponse retVal = ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).AddNum(inValue);
            return retVal.Body.AddNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.AddNumResponse> Calculator_2.ServiceReference1.CalculatorWebServicesSoap.AddNumAsync(Calculator_2.ServiceReference1.AddNumRequest request) {
            return base.Channel.AddNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator_2.ServiceReference1.AddNumResponse> AddNumAsync(int num1, int num2) {
            Calculator_2.ServiceReference1.AddNumRequest inValue = new Calculator_2.ServiceReference1.AddNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.AddNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).AddNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator_2.ServiceReference1.SubNumResponse Calculator_2.ServiceReference1.CalculatorWebServicesSoap.SubNum(Calculator_2.ServiceReference1.SubNumRequest request) {
            return base.Channel.SubNum(request);
        }
        
        public string SubNum(int num1, int num2) {
            Calculator_2.ServiceReference1.SubNumRequest inValue = new Calculator_2.ServiceReference1.SubNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.SubNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Calculator_2.ServiceReference1.SubNumResponse retVal = ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).SubNum(inValue);
            return retVal.Body.SubNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.SubNumResponse> Calculator_2.ServiceReference1.CalculatorWebServicesSoap.SubNumAsync(Calculator_2.ServiceReference1.SubNumRequest request) {
            return base.Channel.SubNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator_2.ServiceReference1.SubNumResponse> SubNumAsync(int num1, int num2) {
            Calculator_2.ServiceReference1.SubNumRequest inValue = new Calculator_2.ServiceReference1.SubNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.SubNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).SubNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator_2.ServiceReference1.MulNumResponse Calculator_2.ServiceReference1.CalculatorWebServicesSoap.MulNum(Calculator_2.ServiceReference1.MulNumRequest request) {
            return base.Channel.MulNum(request);
        }
        
        public string MulNum(int num1, int num2) {
            Calculator_2.ServiceReference1.MulNumRequest inValue = new Calculator_2.ServiceReference1.MulNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.MulNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Calculator_2.ServiceReference1.MulNumResponse retVal = ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).MulNum(inValue);
            return retVal.Body.MulNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.MulNumResponse> Calculator_2.ServiceReference1.CalculatorWebServicesSoap.MulNumAsync(Calculator_2.ServiceReference1.MulNumRequest request) {
            return base.Channel.MulNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator_2.ServiceReference1.MulNumResponse> MulNumAsync(int num1, int num2) {
            Calculator_2.ServiceReference1.MulNumRequest inValue = new Calculator_2.ServiceReference1.MulNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.MulNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).MulNumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Calculator_2.ServiceReference1.DivNumResponse Calculator_2.ServiceReference1.CalculatorWebServicesSoap.DivNum(Calculator_2.ServiceReference1.DivNumRequest request) {
            return base.Channel.DivNum(request);
        }
        
        public string DivNum(int num1, int num2) {
            Calculator_2.ServiceReference1.DivNumRequest inValue = new Calculator_2.ServiceReference1.DivNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.DivNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            Calculator_2.ServiceReference1.DivNumResponse retVal = ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).DivNum(inValue);
            return retVal.Body.DivNumResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Calculator_2.ServiceReference1.DivNumResponse> Calculator_2.ServiceReference1.CalculatorWebServicesSoap.DivNumAsync(Calculator_2.ServiceReference1.DivNumRequest request) {
            return base.Channel.DivNumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Calculator_2.ServiceReference1.DivNumResponse> DivNumAsync(int num1, int num2) {
            Calculator_2.ServiceReference1.DivNumRequest inValue = new Calculator_2.ServiceReference1.DivNumRequest();
            inValue.Body = new Calculator_2.ServiceReference1.DivNumRequestBody();
            inValue.Body.num1 = num1;
            inValue.Body.num2 = num2;
            return ((Calculator_2.ServiceReference1.CalculatorWebServicesSoap)(this)).DivNumAsync(inValue);
        }
    }
}
