//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator_2.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Display_GridviewSoap")]
    public interface Display_GridviewSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayAllRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DisplayAllRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayAllRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DisplayAllRecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertRecord(int id, string ename, string esalary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertRecordAsync(int id, string ename, string esalary);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Display_GridviewSoapChannel : Calculator_2.ServiceReference2.Display_GridviewSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Display_GridviewSoapClient : System.ServiceModel.ClientBase<Calculator_2.ServiceReference2.Display_GridviewSoap>, Calculator_2.ServiceReference2.Display_GridviewSoap {
        
        public Display_GridviewSoapClient() {
        }
        
        public Display_GridviewSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Display_GridviewSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Display_GridviewSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Display_GridviewSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable DisplayAllRecord() {
            return base.Channel.DisplayAllRecord();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DisplayAllRecordAsync() {
            return base.Channel.DisplayAllRecordAsync();
        }
        
        public string insertRecord(int id, string ename, string esalary) {
            return base.Channel.insertRecord(id, ename, esalary);
        }
        
        public System.Threading.Tasks.Task<string> insertRecordAsync(int id, string ename, string esalary) {
            return base.Channel.insertRecordAsync(id, ename, esalary);
        }
    }
}
