//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWT_Practial_Three
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_info
    {
        public byte cid { get; set; }
        public string cname { get; set; }
        public string cadd { get; set; }
    }
}
