//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWT_Practial_Three
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public string pcost { get; set; }

    }
}
