//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_Calcy_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService_CalcySoap")]
    public interface WebService_CalcySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        int addition(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        System.Threading.Tasks.Task<int> additionAsync(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sub", ReplyAction="*")]
        int sub(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> subAsync(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mul", ReplyAction="*")]
        int mul(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> mulAsync(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/div", ReplyAction="*")]
        int div(int n, int p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/div", ReplyAction="*")]
        System.Threading.Tasks.Task<int> divAsync(int n, int p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_CalcySoapChannel : WebService_Calcy_Client.ServiceReference1.WebService_CalcySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_CalcySoapClient : System.ServiceModel.ClientBase<WebService_Calcy_Client.ServiceReference1.WebService_CalcySoap>, WebService_Calcy_Client.ServiceReference1.WebService_CalcySoap {
        
        public WebService_CalcySoapClient() {
        }
        
        public WebService_CalcySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_CalcySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CalcySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CalcySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addition(int n, int p) {
            return base.Channel.addition(n, p);
        }
        
        public System.Threading.Tasks.Task<int> additionAsync(int n, int p) {
            return base.Channel.additionAsync(n, p);
        }
        
        public int sub(int n, int p) {
            return base.Channel.sub(n, p);
        }
        
        public System.Threading.Tasks.Task<int> subAsync(int n, int p) {
            return base.Channel.subAsync(n, p);
        }
        
        public int mul(int n, int p) {
            return base.Channel.mul(n, p);
        }
        
        public System.Threading.Tasks.Task<int> mulAsync(int n, int p) {
            return base.Channel.mulAsync(n, p);
        }
        
        public int div(int n, int p) {
            return base.Channel.div(n, p);
        }
        
        public System.Threading.Tasks.Task<int> divAsync(int n, int p) {
            return base.Channel.divAsync(n, p);
        }
    }
}
