//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator_2.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.Update_WebServiceSoap")]
    public interface Update_WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateProduct(int id, string name, string details, string price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateProductAsync(int id, string name, string details, string price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayAllRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable DisplayAllRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DisplayAllRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> DisplayAllRecordAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Update_WebServiceSoapChannel : Calculator_2.ServiceReference3.Update_WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Update_WebServiceSoapClient : System.ServiceModel.ClientBase<Calculator_2.ServiceReference3.Update_WebServiceSoap>, Calculator_2.ServiceReference3.Update_WebServiceSoap {
        
        public Update_WebServiceSoapClient() {
        }
        
        public Update_WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Update_WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Update_WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Update_WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateProduct(int id, string name, string details, string price) {
            return base.Channel.UpdateProduct(id, name, details, price);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProductAsync(int id, string name, string details, string price) {
            return base.Channel.UpdateProductAsync(id, name, details, price);
        }
        
        public System.Data.DataTable DisplayAllRecord() {
            return base.Channel.DisplayAllRecord();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DisplayAllRecordAsync() {
            return base.Channel.DisplayAllRecordAsync();
        }
    }
}
